# Generated by Django 5.2.7 on 2025-10-05 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformeTrimestral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_area', models.CharField()),
                ('trimester', models.CharField(choices=[('ene-mar', 'Enero-Marzo'), ('abr-jun', 'Abril-Junio'), ('jul-sep', 'Julio-Septiembre'), ('oct-dic', 'Octubre-Diciembre')], default='ene-mar', max_length=7)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('pide', models.CharField(max_length=150)),
                ('cacei', models.CharField(max_length=200)),
                ('created_by', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vo_bo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_num', models.CharField(max_length=10)),
                ('is_specific', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('planificated', models.IntegerField()),
                ('finalized', models.IntegerField()),
                ('cumpliment_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('incumpliment_justification', models.TextField()),
                ('activity_impact', models.TextField()),
                ('detach', models.BooleanField(default=False)),
                ('action_date', models.DateTimeField()),
                ('photograpi_url', models.CharField(blank=True, max_length=200, null=True)),
                ('informe_trimestral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.informetrimestral')),
            ],
        ),
    ]
